### ISSUE TITLE
Feature request: Pretty printing

### ISSUE THREAD

**Issue by voxpelli** [ichiriac/js-compact-diff#1]
Would be very neat to be able to pretty print the output – through just text and/or with colors using eg. [chalk](https://www.npmjs.com/package/chalk)

Would be great for feedback in CLI-tools 🙂

**Comment by ichiriac** [comment]
Hi @voxpelli,

This project is not a CLI command, it's a lightweight, simple & standalone library that handles in-memory objects, without any dependency.

The test.js can be run in output mode because I wanted to make some quick & dirty testing but it's not the point of the library.

If you want to you can for example create another project use this library in order to read some json inputs, and save the output or print in a pretty format for example.

Here the main reason of this library is to handle in memory and next store it with json the states of an application with many nodes and a minimal memory/disk footprint.

A concrete example would be a versioning document system based on JSON documents, if you want to save only changed nodes you can use this, and to rebuild latest version you start with initial document and you apply each diff.
